### PR TITLE
Remove type assertion in list_of_constraint_types

### LINKED ISSUE #2045: type assert failing when displaying `direct_model(Gurobi.Optimizer())`
on creating `direct_model(Gurobi.Optimizer())` when the model object tries to print
```
A JuMP Model
Feasibility problem with:
Variables: 0
Error showing value of type Model:
ERROR: TypeError: in typeassert, expected Array{Tuple{DataType,DataType},1}, got Array{Any,1}
Stacktrace:
 [1] list_of_constraint_types(::Model) at /home/expandingman/.julia/packages/JuMP/iGamg/src/constraints.jl:844
 [2] show_constraints_summary(::IOContext{REPL.Terminals.TTYTerminal}, ::Model) at /home/expandingman/.julia/packages/JuMP/iGamg/src/print.jl:385
 [3] show(::IOContext{REPL.Terminals.TTYTerminal}, ::Model) at /home/expandingman/.julia/packages/JuMP/iGamg/src/print.jl:171
 [4] show(::IOContext{REPL.Terminals.TTYTerminal}, ::MIME{Symbol("text/plain")}, ::Model) at ./multimedia.jl:47
 [5] display(::REPL.REPLDisplay, ::MIME{Symbol("text/plain")}, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:132
 [6] display(::REPL.REPLDisplay, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:136
 [7] display(::Any) at ./multimedia.jl:323
 [8] #invokelatest#1 at ./essentials.jl:790 [inlined]
 [9] invokelatest at ./essentials.jl:789 [inlined]
 [10] print_response(::IO, ::Any, ::Bool, ::Bool, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:156
 [11] print_response(::REPL.AbstractREPL, ::Any, ::Bool, ::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:141
 [12] (::getfield(REPL, Symbol("#do_respond#38")){Bool,getfield(REPL, Symbol("##48#57")){REPL.LineEditREPL,REPL.REPLHistoryProvider},REPL.LineEditREPL,REPL.LineEdit.Prompt})(::Any, ::Any, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:718
 [13] #invokelatest#1 at ./essentials.jl:790 [inlined]
 [14] invokelatest at ./essentials.jl:789 [inlined]
 [15] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/REPL/src/LineEdit.jl:2306
 [16] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:1038
 [17] run_repl(::REPL.AbstractREPL, ::Any) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:201
 [18] (::getfield(Base, Symbol("##737#739")){Bool,Bool,Bool,Bool})(::Module) at ./client.jl:390
 [19] #invokelatest#1 at ./essentials.jl:790 [inlined]
 [20] invokelatest at ./essentials.jl:789 [inlined]
 [21] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:374
 [22] exec_options(::Base.JLOptions) at ./client.jl:312
 [23] _start() at ./client.jl:464
```

### PR DESCRIPTION
**Pull request by odow**
Closes #2045

### CODE REVIEW

**Review by mlubin — APPROVED** [review]

File: src/constraints.jl [hunk 1]
```diff
@@ -971,9 +971,11 @@ julia> list_of_constraint_types(model)
  (VariableRef, MathOptInterface.ZeroOne)
 ```
 """
-function list_of_constraint_types(model::Model)
-    list = MOI.get(
-        model, MOI.ListOfConstraints())::Vector{Tuple{DataType, DataType}}
-    return Tuple{DataType, DataType}[(jump_function_type(model, f), s)
-                                     for (f,s) in list]
+function list_of_constraint_types(model::Model)::Vector{Tuple{DataType, DataType}}
```
Comment (blegat) [inline src/constraints.jl:974]: Why adding the annotation here as we already annotate the element type of the vector

Comment (odow) [reply src/constraints.jl:974]: See the comment below. It didn't infer correctly.
