### PR TITLE
Fix error message for unrecognized sense

### LINKED ISSUE #3310: Improve error message for strict inequalities
x-ref https://discourse.julialang.org/t/cannot-set-an-array-of-constraints-constraint-getting-an-error/96901

### PR DESCRIPTION
**Pull request by odow**
Closes #3310

### CODE REVIEW

File: test/test_macros.jl [hunk 1]
```diff
@@ -1720,11 +1720,21 @@ function test_variable_reverse_sense()
...
+        @variable(model, x ⊕ 1),
+    )
+    return
+end
+
+function test_constraint_unsupported_operator()
+    model = Model()
+    @variable(model, x)
+    @test_macro_throws(
+        ErrorException("In `@constraint(model, x ⊕ 1)`: unsupported operator ⊕"),
```
Comment (odow) [inline test/test_macros.jl:1736]:
```suggestion
        ErrorException(
            "In `@constraint(model, x ⊕ 1)`: unsupported operator ⊕",
        ),
```

**Review by blegat — APPROVED** [review]
