### PR TITLE
Fix constraint tags for broadcast constraints

### LINKED ISSUE #3514: Constraints with broadcasting operators hang with tags
When I attempt to define a vectorized constraint using broadcasting operators and I include a tag, the `@constraint` call just hangs forever:
```julia
using JuMP
m = Model()
@variable(m, x[1:2])
struct MyTag end
@constraint(m, x .<= 2, MyTag()) 
```

### PR DESCRIPTION
**Pull request by odow**
Closes #3514

### CODE REVIEW

File: test/test_macros.jl [hunk 1]
```diff
@@ -2083,4 +2095,40 @@ function test_wrap_let_symbol_models()
...
+    data = ScalarConstraint(c.f, c.s)
+    return add_constraint(model, data, "$(c.name)[$(name)]")
+end
+
+function test_issue_3514()
+    model = Model()
+    @variable(model, x[1:2])
+    @constraint(model, b, 2x .<= 1, Issue3514Tag("a"))
+    @test name.(b) == ["a[b]", "a[b]"]
+    @constraint(model, c, 2x .>= 1, [Issue3514Tag("d"),Issue3514Tag("e")])
```
Comment (odow) [inline test/test_macros.jl:2129]:
```suggestion
    @constraint(model, c, 2x .>= 1, [Issue3514Tag("d"), Issue3514Tag("e")])
```
