### PR TITLE
Fix bug in set_time_limit_sec

### LINKED ISSUE #2805: Optimizer Attributes Not Standardized
Attributes set from JuMP like `MOI.TimeLimitSec` are not standardized to the types that MOI expects, leading to unexpected errors.
```julia
julia> using JuMP

julia> m = Model(mockoptimizer = () -> MOIU.MockOptimizer(MOIU.UniversalFallback(MOIU.Model{Float64}()),  eval_objective_value=false));

julia> set_time_limit_sec(m, 42)

julia>time_limit_sec(m)
ERROR: TypeError: in typeassert, expected Union{Nothing, Float64}, got a value of type Int64       
Stacktrace:
 [1] get(model::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.MockOptimizer{MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}, attr::MathOptInterface.TimeLimitSec)
   @ MathOptInterface.Utilities C:\Users\pulsipher\.julia\packages\MathOptInterface\jPhq9\src\Utilities\cachingoptimizer.jl:938
 [2] get(model::Model, attr::MathOptInterface.TimeLimitSec)
   @ JuMP C:\Users\pulsipher\.julia\packages\JuMP\yP8fy\src\JuMP.jl:1242
 [3] time_limit_sec(model::Model)
   @ JuMP C:\Users\pulsipher\.julia\packages\JuMP\yP8fy\src\JuMP.jl:1018
 [4] top-level scope
   @ REPL[33]:1
```

### PR DESCRIPTION
**Pull request by odow**
Closes #2805

### CODE REVIEW

File: src/JuMP.jl [hunk 1]
```diff
@@ -990,8 +990,8 @@ Can be unset using [`unset_time_limit_sec`](@ref) or with `limit` set to
 
 See also: [`unset_time_limit_sec`](@ref), [`time_limit_sec`](@ref).
 """
-function set_time_limit_sec(model::Model, limit)
-    return MOI.set(model, MOI.TimeLimitSec(), limit)
+function set_time_limit_sec(model::Model, limit::Real)
```
Comment (blegat) [inline src/JuMP.jl:993]: `limit` can be `nothing` as well, see CI failure

Comment (odow) [reply src/JuMP.jl:993]: People should use `unset_time_limit_sec` in that case. But yeah, I'll change.
