### PR TITLE
[Containers] use OrderedDict as the data structure for SparseAxisArray

### LINKED ISSUE #3678: Iterating SparseAxisArray does not preserve order
x-ref https://discourse.julialang.org/t/unexpected-jump-variable-order-when-indexed-by-tuple/110262

```julia
julia> using JuMP

julia> model = Model();

julia> N = 1:2;

julia> M = [[1.0, 11.0, 100.0], [0.0, 17.0, 104.0]];

julia> @variable(model, foo[n in N, M[n]])
JuMP.Containers.SparseAxisArray{VariableRef, 2, Tuple{Int64, Float64}} with 6 entries:
  [1, 1.0  ]  =  foo[1,1.0]
  [1, 100.0]  =  foo[1,100.0]
  [1, 11.0 ]  =  foo[1,11.0]
  [2, 0.0  ]  =  foo[2,0.0]
  [2, 104.0]  =  foo[2,104.0]
  [2, 17.0 ]  =  foo[2,17.0]

julia> foo.data
Dict{Tuple{Int64, Float64}, VariableRef} with 6 entries:
  (2, 17.0)  => foo[2,17.0]
  (1, 11.0)  => foo[1,11.0]
  (1, 1.0)   => foo[1,1.0]
  (1, 100.0) => foo[1,100.0]
  (2, 0.0)   => foo[2,0.0]
  (2, 104.0) => foo[2,104.0]

julia> @constraint(model, foo[1, :] in SecondOrderCone())
[foo[1,11.0], foo[1,1.0], foo[1,100.0]] ∈ MathOptInterface.SecondOrderCone(3)
```

User could reasonably expect constraint function to be `[foo[1,1.0], foo[1,11.0], foo[1,100.0]]`.

This is because we store the data in a `Dict`.

We could swap to an `OrderedDict`, or throw an error or a warning when we convert a `SparseAxisArray` to a vector.

### PR DESCRIPTION
**Pull request by odow**
Closes #3678 
Closes #3680

The issue is still really that `SparseAxisArray` is not a regular n-dimensional Array. Each slice can have a different length with different axes. It doesn't make sense to support a lot of operations with it.

The only thing that we should support are vectors.

This PR has the problem that the current iteration order is the transpose of what it "should" be (row-major, instead of column-major). 

This is needed because the second and subsequent dimensions can depend on the first and prior. So it isn't really meaningful to iterate "down" the first index holding all else constant.

I can see this being a constant source of future problems.

### CODE REVIEW

File: src/Containers/SparseAxisArray.jl [hunk 1]
```diff
@@ -448,7 +464,6 @@ function Base.show(io::IOContext, x::SparseAxisArray)
         (i, (key, value)) in enumerate(x.data) if
         i < half_screen_rows || i > length(x) - half_screen_rows
     ]
-    sort!(key_strings; by = x -> x[1])
```
Comment (odow) [inline src/Containers/SparseAxisArray.jl:451]: I didn't run the full tests locally, but from what I can tell, there are few, if any, printing changes, because we used to sort the keys, and most tests/examples provided the keys in a nice sorted order.

File: src/Containers/SparseAxisArray.jl [hunk 2]
```diff
@@ -5,28 +5,32 @@
...
+julia> dict = OrderedDict((:a, 2) => 1.0, (:a, 3) => 2.0, (:b, 3) => 3.0)
+OrderedDict{Tuple{Symbol, Int64}, Float64} with 3 entries:
+  (:a, 2) => 1.0
   (:a, 3) => 2.0
   (:b, 3) => 3.0
-  (:a, 2) => 1.0
 
 julia> array = Containers.SparseAxisArray(dict)
-SparseAxisArray{Float64, 2, Tuple{Symbol, Int64}} with 3 entries:
+JuMP.Containers.SparseAxisArray{Float64, 2, Tuple{Symbol, Int64}} with 3 entries:
```
Comment (odow) [inline src/Containers/SparseAxisArray.jl:33]:
```suggestion
SparseAxisArray{Float64, 2, Tuple{Symbol, Int64}} with 3 entries:
```

**Comment by joaquimg** [comment]
Shouldnt the iteration ordering comment be part of docs?

**Comment by odow** [comment]
Yeah. I guess my first question is: should we do this? 

If we do, we need more docs on the specifics of the order and slicing, and when things can go wrong.

Also: https://github.com/jump-dev/JuMP.jl/actions/runs/7944311147

**Comment by joaquimg** [comment]
The slicing issues you showed seem pretty dangerous.

The only downside would be the performance penalty? Did you benchmark it?

**Comment by odow** [comment]
> The only downside would be the performance penalty? Did you benchmark it?

I didn't benchmark it, but I think the risk of incorrect usage outweighs the cost.

It's probably slower because creating an ordered dict is slower. But it shouldn't be too bad.

**Comment by joaquimg** [comment]
I agree correctness must come first.

Is there any other downside?

**Comment by odow** [comment]
I added a warning.

I guess the main downside is that existing iteration orders may change. But that could have happened anyway, because we used a `Dict`.

**Review by blegat — APPROVED** [review]
The change of order of `eachindex` is indeed sub-optimal since we want `SparseAxisArrays` to match the behavior of `Array` it is dense and it's indices are `Base.OneTo`. However, it doesn't seem that this could be done in general and it's still a strict improvement to the behavior before this PR.

File: docs/src/manual/containers.md [hunk 3]
```diff
@@ -315,13 +315,28 @@ JuMP.Containers.SparseAxisArray{Tuple{Int64, Symbol}, 1, Tuple{Int64}} with 2 en
...
            println(y[key])
        end
 (2, :B)
 (3, :B)
 ```
 
+!!! warning
+    In contrast to `Base.Array`s, which iterate in column-major order, that is,
+    by varying indices from left to right, `SparseAxisArray` iterates in
+    row-major order, that is, by varying the indices from right to left. As an
```
Comment (mlubin) [inline docs/src/manual/containers.md:336]: Is this true in general or only when the `SparseAxisArray` is created by a macro? If you construct using a dict then the iteration order will match the given dict, right?

Comment (odow) [reply docs/src/manual/containers.md:336]: Only when created by a macro. Dict order is as given.

Comment (odow) [reply docs/src/manual/containers.md]: Tweaked the wording slightly.

**Comment by odow** [comment]
I audited all the open issues. I think we're safe from the `delete` segfault because you cannot delete elements in a `SparseAxisArray`.

The most up for debate issue is: https://github.com/JuliaCollections/OrderedCollections.jl/issues/82

```Julia
julia> Containers.@container(x[k in 1:2], k, container = SparseAxisArray)
JuMP.Containers.SparseAxisArray{Int64, 1, Tuple{Int64}} with 2 entries:
  [1]  =  1
  [2]  =  2

julia> Containers.@container(y[k in 2:-1:1], k, container = SparseAxisArray)
JuMP.Containers.SparseAxisArray{Int64, 1, Tuple{Int64}} with 2 entries:
  [2]  =  2
  [1]  =  1

julia> x == y
true
```

But this coincidentally just reproduces the behavior of the current JuMP:
```julia
julia> Containers.@container(x[k in 1:2], k, container = SparseAxisArray)
JuMP.Containers.SparseAxisArray{Int64, 1, Tuple{Int64}} with 2 entries:
  [1]  =  1
  [2]  =  2

julia> Containers.@container(y[k in 2:-1:1], k, container = SparseAxisArray)
JuMP.Containers.SparseAxisArray{Int64, 1, Tuple{Int64}} with 2 entries:
  [1]  =  1
  [2]  =  2

julia> x == y
true
```

**Comment by mlubin** [comment]
https://github.com/JuliaCollections/OrderedCollections.jl/issues/82 isn't too concerning to me.

**Comment by odow** [comment]
So good to merge then?

**Review by mlubin — APPROVED** [review]
