### PR TITLE
Fix solution_summary when there are duplicate names

### LINKED ISSUE #3847: solution_summary with duplicate names
I found this confusing:

image

### PR DESCRIPTION
**Pull request by odow**
Closes #3847

### CODE REVIEW

File: test/test_solution_summary.jl [hunk 1]
```diff
@@ -205,4 +205,55 @@ function test_solution_summary_vector_dual()
...
+      Result count       : 1
+      Termination status : OPTIMAL
+      Message from the solver:
+      "solver specific string"
+
+    * Candidate solution (result #1)
+      Primal status      : FEASIBLE_POINT
+      Dual status        : FEASIBLE_POINT
+      Objective value    : 0.00000e+00
+      Dual objective value : 5.00000e+00
```
Comment (odow) [inline test/test_solution_summary.jl:245]:
```suggestion
      Dual objective value : 1.10000e+01
```
