### PR TITLE
Fix error message for invalid indicator constraints

### LINKED ISSUE #3581: MethodError: no method matching `isless(::Int64, ::QuadExpr)` / `isless(::VariableRef, ::QuadExpr)`
```
using JuMP, SCIP

model = Model(SCIP.Optimizer)

@variable(model, a)
@variable(model, b)
@variable(model, c)

@variable(model, d)
@variable(model, e)

@constraint(model, (a*b >= c) => {d == e})

print(model)
```
```
MethodError: no method matching isless(::VariableRef, ::QuadExpr)

Closest candidates are:
  isless(::Any, ::Missing)
   @ Base missing.jl:88
  isless(::Missing, ::Any)
   @ Base missing.jl:87


Stacktrace:
 [1] <(x::VariableRef, y::QuadExpr)
   @ Base ./operators.jl:343
 [2] <=(x::VariableRef, y::QuadExpr)
   @ Base ./operators.jl:392
 [3] >=(x::QuadExpr, y::VariableRef)
   @ Base ./operators.jl:416
 [4] macro expansion
   @ ~/.julia/packages/JuMP/D44Aq/src/macros.jl:1345 [inlined]
 [5] top-level scope
   @ In[30]:12
```

```
using JuMP, SCIP

model = Model(SCIP.Optimizer)

@variable(model, a)
@variable(model, b)

@variable(model, d)
@variable(model, e)

@constraint(model, (a*b >= 42) => {d == e})

print(model)
```
```
MethodError: no method matching isless(::Int64, ::QuadExpr)

Closest candidates are:
  isless(::Integer, ::ForwardDiff.Dual{Ty}) where Ty
   @ ForwardDiff ~/.julia/packages/ForwardDiff/PcZ48/src/dual.jl:145
  isless(::Real, ::AbstractFloat)
   @ Base operators.jl:178
  isless(::Real, ::ForwardDiff.Dual{Ty}) where Ty
   @ ForwardDiff ~/.julia/packages/ForwardDiff/PcZ48/src/dual.jl:145
  ...


Stacktrace:
 [1] <(x::Int64, y::QuadExpr)
   @ Base ./operators.jl:343
 [2] <=(x::Int64, y::QuadExpr)
   @ Base ./operators.jl:392
 [3] >=(x::QuadExpr, y::Int64)
   @ Base ./operators.jl:416
 [4] macro expansion
   @ ~/.julia/packages/JuMP/D44Aq/src/macros.jl:1345 [inlined]
 [5] top-level scope
   @ In[33]:11
```

If i launder `a*b >= c` through an `expression`, https://github.com/jump-dev/JuMP.jl/issues/3580 happens.

### PR DESCRIPTION
**Pull request by odow**
Closes #3581

### CODE REVIEW

File: test/test_constraint.jl [hunk 1]
```diff
@@ -1783,4 +1783,14 @@ function test_SkipModelConvertScalarSetWrapper()
     return
 end
 
+function test_indicator_error()
+    model = Model()
+    @variable(model, x[1:2])
+    err = ErrorException(
+        "In `@constraint(model, x[1] >= 0 --> {x[2] == 0})`: unable to build indicator constraint with the left-hand side term `(x[1] >= 0)::NonlinearExpr`. The left-hand side must be a binary decision variable.",
```
Comment (odow) [inline test/test_constraint.jl:1790]:
```suggestion
        "In `@constraint(model, x[1] >= 0 --> {x[2] == 0})`: unable to build indicator constraint with the left-hand side term `(x[1] >= 0)::JuMP.NonlinearExpr`. The left-hand side must be a binary decision variable.",
```

**Comment by LebedevRI** [comment]
@odow thank you!
