### PR TITLE
Fix linearity check of user-defined function

### LINKED ISSUE #2340: BoundsError in NLP classify_linearity
```Julia
(jump) pkg> st
Status `/private/tmp/jump/Project.toml`
  [b6b21f68] Ipopt v0.6.3
  [4076af6c] JuMP v0.21.5

julia> using JuMP, Ipopt

julia> model = Model(Ipopt.Optimizer)
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: EMPTY_OPTIMIZER
Solver name: Ipopt

julia> @variable(model, x)
x

julia> foo(x, y) = x + y
foo (generic function with 1 method)

julia> register(model, :foo, 2, foo, autodiff=true)

julia> ex = @NLexpression(model, foo(x^2, x))
"Reference to nonlinear expression #1"

julia> @NLobjective(model, Max, ex)

julia> optimize!(model)
ERROR: BoundsError: attempt to access 8-element Array{Symbol,1} at index [9]
Stacktrace:
 [1] getindex at ./array.jl:809 [inlined]
 [2] classify_linearity(::Array{JuMP._Derivatives.NodeData,1}, ::SparseArrays.SparseMatrixCSC{Bool,Int64}, ::Array{JuMP._Derivatives.Linearity,1}) at /Users/oscar/.julia/packages/JuMP/qhoVb/src/_Derivatives/linearity.jl:42
 [3] JuMP._SubexpressionStorage(::Array{JuMP._Derivatives.NodeData,1}, ::Array{Float64,1}, ::Int64, ::Array{JuMP._Derivatives.Linearity,1}, ::Dict{MathOptInterface.VariableIndex,Int64}) at /Users/oscar/.julia/packages/JuMP/qhoVb/src/nlp.jl:300
 [4] initialize(::NLPEvaluator, ::Array{Symbol,1}) at /Users/oscar/.julia/packages/JuMP/qhoVb/src/nlp.jl:363
 [5] optimize!(::Ipopt.Optimizer) at /Users/oscar/.julia/packages/Ipopt/bYzBL/src/MOI_wrapper.jl:1041
 [6] optimize!(::MathOptInterface.Bridges.LazyBridgeOptimizer{Ipopt.Optimizer}) at /Users/oscar/.julia/packages/MathOptInterface/k7UUH/src/Bridges/bridge_optimizer.jl:264
 [7] optimize!(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}) at /Users/oscar/.julia/packages/MathOptInterface/k7UUH/src/Utilities/cachingoptimizer.jl:215
 [8] optimize!(::Model, ::Nothing; bridge_constraints::Bool, ignore_optimize_hook::Bool, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /Users/oscar/.julia/packages/JuMP/qhoVb/src/optimizer_interface.jl:130
 [9] optimize! at /Users/oscar/.julia/packages/JuMP/qhoVb/src/optimizer_interface.jl:106 [inlined] (repeats 2 times)
 [10] top-level scope at REPL[11]:1
```

Reported by @mfairley

### PR DESCRIPTION
**Pull request by odow**
Closes #2340

### CODE REVIEW

File: src/_Derivatives/linearity.jl [hunk 1]
```diff
@@ -38,8 +38,10 @@ function classify_linearity(nd::Vector{NodeData},adj,subexpression_linearity)
             if any_nonlinear
                 # if any children are nonlinear, then we're nonlinear
                 linearity[k] = NONLINEAR
-                # except in the case of ifelse. if the operands are linear then we're piecewise linear
-                if nod.nodetype == CALL && operators[nod.index] == :ifelse
+                # except in the case of ifelse. If the operands are linear then
+                # we're piecewise linear. `nod.index` may be larger than
+                # `operators`, so we use `get`.
+                if nod.nodetype == CALL && get(operators, nod.index, :not_ifelse) == :ifelse
```
Comment (mlubin) [inline src/_Derivatives/linearity.jl:44]: It would be more consistent with the code below to do something like:
``nod.index < USER_OPERATOR_ID_START && operators[nod.index] == :ifelse``

**Review by mlubin — COMMENTED** [review]
I'm surprised this bug has gone unnoticed for so long.
