### PR TITLE
[Containers] disallow CartesianIndex as a key for DenseAxisArray

### LINKED ISSUE #2825: CartesianIndex as keys in a DenseAxisArray
Reported on SO: https://stackoverflow.com/questions/70284721/julia-jump-how-to-use-variable-with-cartesianindex/70296103

There's some weird things that happen:
```Julia
julia> model = Model()
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.

julia> S = CartesianIndex.([2, 4])
2-element Vector{CartesianIndex{1}}:
 CartesianIndex(2,)
 CartesianIndex(4,)

julia> @variable(model, x[S])
1-dimensional DenseAxisArray{VariableRef,1,...} with index sets:
    Dimension 1, CartesianIndex{1}[CartesianIndex(2,), CartesianIndex(4,)]
And data, a 2-element Vector{VariableRef}:
 x[CartesianIndex(2,)]
 x[CartesianIndex(4,)]

julia> x[CartesianIndex(2,)]
x[CartesianIndex(4,)]

julia> x[CartesianIndex(1,)]
x[CartesianIndex(2,)]

julia> x[CartesianIndex(4,)]
ERROR: BoundsError: attempt to access 2-element Vector{VariableRef} at index [4]
Stacktrace:
 [1] getindex
   @ ./array.jl:801 [inlined]
 [2] getindex
   @ ./multidimensional.jl:637 [inlined]
 [3] getindex(A::JuMP.Containers.DenseAxisArray{VariableRef, 1, Tuple{Vector{CartesianIndex{1}}}, Tuple{JuMP.Containers._AxisLookup{Dict{CartesianIndex{1}, Int64}}}}, idx::CartesianIndex{1})
   @ JuMP.Containers ~/.julia/packages/JuMP/2IF9U/src/Containers/DenseAxisArray.jl:323
 [4] top-level scope
   @ REPL[42]:1
```

### PR DESCRIPTION
**Pull request by odow**
Technically breaking, but it has buggy behavior at present, so this is a bug-fix. 

We don't want cartesian indices as indices. They're not intended for that purpose. The original poster on stack overflow should use a different approach: https://stackoverflow.com/questions/70284721/julia-jump-how-to-use-variable-with-cartesianindex/70296103

Closes #2825

### CODE REVIEW

File: src/Containers/DenseAxisArray.jl [hunk 1]
```diff
@@ -148,17 +148,26 @@ function Base.get(
     return get(x.data, key[1] => key[2], default)
 end
 
-_abstract_vector(x::AbstractVector) = x
+function _abstract_vector(x::AbstractVector)
```
Comment (blegat) [inline src/Containers/DenseAxisArray.jl:151]: Can't you do that with dispatch `_abstract_vector(::AbstractVector{<:CartesianIndex}) = error...`

File: src/Containers/DenseAxisArray.jl [hunk 2]
```diff
@@ -148,17 +148,26 @@ function Base.get(
...
+            "Unsupported index type `CartesianIndex` in axis: $x. Cartesian " *
+            "indices are restricted for indexing into and iterating over " *
+            "multidimensional arrays.",
+        )
+    end
+    return x
+end
 
-_abstract_vector(x) = [a for a in x]
+_abstract_vector(x) = _abstract_vector(vec([a for a in x]))
```
Comment (blegat) [inline src/Containers/DenseAxisArray.jl:162]: What is `vec` here for ?

Comment (odow) [reply src/Containers/DenseAxisArray.jl]: I don't remember. I've removed it to see which test broke.

Comment (odow) [reply src/Containers/DenseAxisArray.jl]: I added a test. It was for when the index set is an AbstractArray, not an AbstractVector.
