### PR TITLE
Make NonlinearExpression <: AbstractJuMPScalar

### LINKED ISSUE #2635: Error message improvement for value(Array of NLexpression)
When calling `value(u)` where `u` is an array of variables the following error shows up
```julia
julia> value(u)
ERROR: `JuMP.value` is not defined for collections of JuMP types. Use Julia's broadcast syntax instead: `JuMP.value.(x)`.
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] value(#unused#::Matrix{VariableRef})
   @ JuMP C:\Users\user\.julia\packages\JuMP\Xrr7O\src\variables.jl:1204
```
This error is helpful.

On the other hand, when calling `value(u)` where `u` is an array of nonlinear expressions the error is
```julia
ERROR: LoadError: MethodError: no method matching value(::Matrix{NonlinearExpression})
```
This is not as helpful as it does not say that `value.` should be used instead.

### PR DESCRIPTION
**Pull request by odow**
Closes #2635

### CODE REVIEW

File: src/JuMP.jl [hunk 1]
```diff
@@ -1370,7 +1370,7 @@ A struct to represent a nonlinear expression.
 
 Create an expression using [`@NLexpression`](@ref).
 """
-struct NonlinearExpression
+struct NonlinearExpression <: AbstractJuMPScalar
```
Comment (blegat) [inline src/JuMP.jl:1373]: Update docstring as well?
