### PR TITLE
Fix bug broadcasting constraints with sparse terms

### LINKED ISSUE #2162: Better error message for sparse RHS terms in vector constraints
The following code fragment adds additional redundant constraints:

```julia
julia> m = JuMP.Model(glpk_optimizer)
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: EMPTY_OPTIMIZER
Solver name: GLPK

julia> A = sparse([1, 2], [1, 2], [1, 1])
2×2 SparseMatrixCSC{Int64,Int64} with 2 stored entries:
  [1, 1]  =  1
  [2, 2]  =  1

julia> b = sparsevec([1, 2], [1, 2])
2-element SparseVector{Int64,Int64} with 2 stored entries:
  [1]  =  1
  [2]  =  2

julia> JuMP.@variable(m, x[1:2])
2-element Array{VariableRef,1}:
 x[1]
 x[2]

julia> JuMP.@constraint(m, A * x .<= b)
2-element SparseVector{ConstraintRef{Model,_1,ScalarShape} where _1,Int64} with 2 stored entries:
  [1]  =  x[1] ≤ 1.0
  [2]  =  x[2] ≤ 2.0

julia> m
A JuMP Model
Feasibility problem with:
Variables: 2
`GenericAffExpr{Float64,VariableRef}`-in-`MathOptInterface.LessThan{Float64}`: 3 constraints
Model mode: AUTOMATIC
CachingOptimizer state: EMPTY_OPTIMIZER
Solver name: GLPK
Names registered in the model: x

julia> println(m)
Feasibility
Subject to
 0 ≤ 0.0
 x[1] ≤ 1.0
 x[2] ≤ 2.0

JuMP.@constraint(m, Matrix(A) * x .>= Vector(b))
2-element Array{ConstraintRef{Model,MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.GreaterThan{Float64}},ScalarShape},1}:
 x[1] ≥ 1.0
 x[2] ≥ 2.0

julia> m
A JuMP Model
Feasibility problem with:
Variables: 2
`GenericAffExpr{Float64,VariableRef}`-in-`MathOptInterface.GreaterThan{Float64}`: 2 constraints
`GenericAffExpr{Float64,VariableRef}`-in-`MathOptInterface.LessThan{Float64}`: 3 constraints
Model mode: AUTOMATIC
CachingOptimizer state: EMPTY_OPTIMIZER
Solver name: GLPK
Names registered in the model: x

julia> println(m)
Feasibility
Subject to
 x[1] ≥ 1.0
 x[2] ≥ 2.0
 0 ≤ 0.0
 x[1] ≤ 1.0
 x[2] ≤ 2.0
```

Why is an additional ``0 ≤ 0.0`` constraint getting added when using sparse matrices. This does not seem to be an issue when using dense matrices.

### PR DESCRIPTION
**Pull request by odow**
Closes #2162 

Needs https://github.com/jump-dev/MutableArithmetics.jl/pull/95

### CODE REVIEW

File: src/macros.jl [hunk 1]
```diff
@@ -184,9 +184,40 @@ function sense_to_set(_error::Function, ::Val{S}) where {S}
...
+have serious consequences! In our case, broadcasting `build_constraint` will add
+a new `0 = 0` constraint.
+
+To avoid this, make sure to `_desparsify` any arguments that might be
+SparseArrays when broadcasting!
+
+Here's an example of what is happening:
+
+```julia
+julia> foo.(sparsevec([1, 2], [1, 2]))
```
Comment (blegat) [inline src/macros.jl:206]: The foo function is not defined

File: src/macros.jl [hunk 2]
```diff
@@ -184,9 +184,40 @@ function sense_to_set(_error::Function, ::Val{S}) where {S}
...
+
+If `x` is an `AbstractSparseArray`, return the dense equivalent, otherwise just
+return `x`.
+
+## Why is this needed?
+
+When broadcasting `f.(x)` over an `AbstractSparseArray` `x`, Julia first calls
+the equivalent of `f(zero(eltype(x))`. However, if `f` is mutating, this can
+have serious consequences! In our case, broadcasting `build_constraint` will add
+a new `0 = 0` constraint.
```
Comment (blegat) [inline src/macros.jl:198]: How does `collect` help ? It also replaces the structural zero elements with zeros

File: test/macros.jl [hunk 3]
```diff
@@ -801,6 +802,19 @@ end
             @NLparameter(m, p[m = 1:2] == m),
         )
     end
+
+    @testset "Broadcasting sparse arrays" begin
+        model = Model()
+        A = sparse([1, 2], [1, 2], [1, 1])
+        b = sparsevec([1, 2], [1, 2])
+        @variable(model, x[1:2])
+        le_cons = @constraint(model, A * x .<= b)
```
Comment (blegat) [inline test/macros.jl:811]: In this examples, the sparse vectors are dense, can you add an example with structural zero elements ?

File: src/macros.jl (hunk 2 above)
Comment (odow) [reply src/macros.jl]: In most cases (all cases?), promotion means that the incoming SparseArray is actually dense.

In 0.21.7, you get
```Julia
julia> model = Model()
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.

julia> @variable(model, x[1:2])
2-element Vector{VariableRef}:
 x[1]
 x[2]

julia> d = sparsevec([1, 3], x)
3-element SparseVector{VariableRef, Int64} with 2 stored entries:
  [1]  =  x[1]
  [3]  =  x[2]

julia> @constraint(model, d .== 0)
3-element SparseVector{Any, Int64} with 3 stored entries:
  [1]  =  x[1] = 0.0
  [2]  =  0 = 0.0
  [3]  =  x[2] = 0.0

julia> model
A JuMP Model
Feasibility problem with:
Variables: 2
`AffExpr`-in-`MathOptInterface.EqualTo{Float64}`: 4 constraints
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.
Names registered in the model: x
```

In this PR, you get
```Julia
julia> model = Model()
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.

julia> @variable(model, x[1:2])
2-element Vector{VariableRef}:
 x[1]
 x[2]

julia> d = sparsevec([1, 3], x)
3-element SparseVector{VariableRef, Int64} with 2 stored entries:
  [1]  =  x[1]
  [3]  =  x[2]

julia> @constraint(model, d .== 0)
3-element Vector{ConstraintRef{Model, MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64}, MathOptInterface.EqualTo{Float64}}, ScalarShape}}:
 x[1] = 0.0
 0 = 0.0
 x[2] = 0.0

julia> model
A JuMP Model
Feasibility problem with:
Variables: 2
`AffExpr`-in-`MathOptInterface.EqualTo{Float64}`: 3 constraints
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.
Names registered in the model: x
```

Is changing the return type of `@constraint` here breaking? The type change happens with dense constraints too.

File: src/macros.jl [hunk 4]
```diff
@@ -184,9 +184,52 @@ function sense_to_set(_error::Function, ::Val{S}) where {S}
...
+  [1]  =  1
+  [2]  =  2
+```
+
+However, if `f` is mutating, this can have serious consequences! In our case,
+broadcasting `build_constraint` will add a new `0 = 0` constraint.
+
+SparseArrays most-often arise when some input data to the constraint is sparse
+(e.g., a constant vector or matrix). Due to promotion and arithmetic, this
+results in a constraint function that is represented by a SparseArray, but is
```
Comment (blegat) [inline src/macros.jl:218]:
```julia
julia> using SparseArrays

julia> SparseArray
ERROR: UndefVarError: SparseArray not defined

julia> AbstractSparseArray
AbstractSparseArray
```

**Review by blegat — APPROVED** [review]

**Comment by odow** [comment]
What was the conclusion on changing the return type of `@constraint`?

**Comment by blegat** [comment]
I wouldn't consider it breaking. Having a sparse vector of constraint refs can be considered a bug for 2 reasons:  1) zero is not defined for constraint refs. 2) this is dense so it does not make sense to returns it sparse
