### PR TITLE
Fix variable_ref_type for unsupported types and GenericNonlinearExpr

### LINKED ISSUE #3555: `variable_ref_type` induces `StackOverFlowError`
I am working on adding support for `GenericModel` in DisjunctiveProgramming and have run into some consistencies with `variable_ref_type`. First, calling it on `Type{GenericNonlinearExpr}` induces a stack overflow error which is not the case for affine/quadratic expressions:
```julia
julia> variable_ref_type(GenericAffExpr{Int, GenericVariableRef{Int}})
GenericVariableRef{Int64}

julia> variable_ref_type(GenericQuadExpr{Int, GenericVariableRef{Int}})
GenericVariableRef{Int64}

julia> variable_ref_type(GenericNonlinearExpr{GenericVariableRef{Int}})
ERROR: StackOverflowError:
Stacktrace:
 [1] variable_ref_type(#unused#::Type{DataType}) (repeats 79984 times)
   @ ~\.julia\packages\JuMP\D44Aq\src\variables.jl:225
```
Moreover, calling `variable_ref_type` on unsupported types leads to stack overflow errors in general:
```julia
julia> struct MyModel <: AbstractModel end;

julia> variable_ref_type(MyModel)
ERROR: StackOverflowError:
Stacktrace:
 [1] variable_ref_type(#unused#::Type{DataType}) (repeats 79984 times)
   ~\.julia\packages\JuMP\D44Aq\src\variables.jl:225

julia> variable_ref_type(Vector{AffExpr})
ERROR: StackOverflowError:
Stacktrace:
 [1] variable_ref_type(#unused#::Type{DataType}) (repeats 79984 times)
   ~\.julia\packages\JuMP\D44Aq\src\variables.jl:225
```
Granted this is only intended for package developers and requires that it be appropriately extended for each new type, but the stack overflow error made it difficult to debug that I was accidently passing a `Vector` to `variable_ref_type`.

### PR DESCRIPTION
**Pull request by odow**
Closes #3555

### CODE REVIEW

File: test/test_variable.jl [hunk 1]
```diff
@@ -1555,4 +1555,18 @@ function test_parameter_arrays()
     return
 end
 
+function test_variable_ref_type_unsupported()
+    for F in (Vector{VariableRef}, Vector{Int})
+        @test_throws(
+            ErrorException(
+                "Unable to compute the `variable_ref_type` of the type $F`. If you " *
```
Comment (odow) [inline test/test_variable.jl:1562]:
```suggestion
                "Unable to compute the `variable_ref_type` of the type `$F`. If you " *
```

File: src/variables.jl [hunk 2]
```diff
@@ -224,6 +224,14 @@ variable type associated with the model or expression type `F`.
 """
 variable_ref_type(::F) where {F} = variable_ref_type(F)
 
+function variable_ref_type(::Type{F}) where {F}
+    return error(
+        "Unable to compute the `variable_ref_type` of the type `$F`. If you " *
+        "are developing a JuMP extension, defined a new method for " *
```
Comment (odow) [inline src/variables.jl:230]:
```suggestion
        "are developing a JuMP extension, define a new method for " *
```

File: test/test_variable.jl [hunk 3]
```diff
@@ -1555,4 +1555,18 @@ function test_parameter_arrays()
     return
 end
 
+function test_variable_ref_type_unsupported()
+    for F in (Vector{VariableRef}, Vector{Int})
+        @test_throws(
+            ErrorException(
+                "Unable to compute the `variable_ref_type` of the type `$F`. If you " *
+                "are developing a JuMP extension, defined a new method for " *
```
Comment (odow) [inline test/test_variable.jl:1563]:
```suggestion
                "are developing a JuMP extension, define a new method for " *
```

File: test/test_variable.jl [hunk 4]
```diff
@@ -1555,4 +1555,18 @@ function test_parameter_arrays()
...
+                "`JuMP.variable_ref_type(::Type{$F}`",
```
Comment (odow) [inline test/test_variable.jl:1564]:
```suggestion
                "`JuMP.variable_ref_type(::Type{$F})`",
```
