### PR TITLE
Fix LinearAlgebra.hermitian(::AbstractJuMPScalar, ::Symbol)

### LINKED ISSUE #3692: LinearAlgebra.hermitian is incorrect
https://github.com/jump-dev/JuMP.jl/blob/119569556f5fd28d12b012f4c94d8dfdaca6d65a/src/JuMP.jl#L1058
doesn't seem to match the docstring of `LinearAlgebra.hermitian`:

> If `A` is a Number, its real part is returned converted back to the input type.

### PR DESCRIPTION
**Pull request by odow**
Closes #3692

Docstrinng is:
```julia
help?> LinearAlgebra.hermitian
  hermitian(A, uplo=:U)

  Construct a hermitian view of A. If A is a matrix, uplo controls whether the upper (if uplo = :U)
  or lower (if uplo = :L) triangle of A is used to implicitly fill the other one. If A is a Number,
  its real part is returned converted back to the input type.

  If a hermitian view of a matrix is to be constructed of which the elements are neither matrices
  nor numbers, an appropriate method of hermitian has to be implemented. In that case,
  hermitian_type has to be implemented, too.
```

The important sentence is: `If A is a Number, its real part is returned converted back to the input type.`

### CODE REVIEW

File: test/test_complex.jl [hunk 1]
```diff
@@ -310,4 +310,17 @@ function test_hermitian_generic_number_type()
     return
 end
 
+function test_hermitian_jump_scalar()
+    model = Model()
+    @variable(model, X[1:2,1:2] in HermitianPSDCone())
```
Comment (odow) [inline test/test_complex.jl:315]:
```suggestion
    @variable(model, x[1:2, 1:2] in HermitianPSDCone())
```

File: test/test_complex.jl [hunk 2]
```diff
@@ -310,4 +310,17 @@ function test_hermitian_generic_number_type()
...
+    Y = im * x.data
+    Z = [0 real(x[1,2])*im-imag(x[1,2]); -real(x[1,2])*im-imag(x[1,2]) 0]
```
Comment (odow) [inline test/test_complex.jl:317]:
```suggestion
    Z = [0 real(x[1, 2])*im-imag(x[1, 2]); -real(x[1, 2])*im-imag(x[1, 2]) 0]
```
