### PR TITLE
Fix stability of operators with Complex args

### LINKED ISSUE #3071: Failure to multiply real variable with complex matrix
I was under the impression that some elementary support for complex variables or expressions had been merged. The example below uses real variables but complex coefficients. The ultimate goal is to perform some complex computations resulting in a real constraint.
```julia
JuMP v1.3.0
MathOptInterface v1.8.0
```
```julia
julia> using JuMP

julia> model = JuMP.Model()
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: NO_OPTIMIZER
Solver name: No optimizer attached.

julia> JuMP.@variable(model, pv[1:3])
3-element Vector{VariableRef}:
 pv[1]
 pv[2]
 pv[3]

julia> K = randn(ComplexF64, 3,3);

julia> K*pv
ERROR: MethodError: no method matching zero(::Type{Union{GenericAffExpr{ComplexF64, VariableRef}, AffExpr}})
Closest candidates are:
  zero(::Union{Type{P}, P}) where P<:Dates.Period at ~/julia-1.8.1/share/julia/stdlib/v1.8/Dates/src/periods.jl:53
  zero(::ControlSystemsBase.SisoZpk) at ~/.julia/dev/ControlSystems/lib/ControlSystemsBase/src/types/SisoTfTypes/SisoZpk.jl:44
  zero(::MonteCarloMeasurements.StaticParticles{T, N}) where {T, N} at ~/.julia/dev/MonteCarloMeasurements/src/register_primitive.jl:94
  ...
Stacktrace:
 [1] operate!
   @ ~/.julia/packages/MutableArithmetics/Lnlkl/src/implementations/LinearAlgebra.jl:354 [inlined]
 [2] operate_to!
   @ ~/.julia/packages/MutableArithmetics/Lnlkl/src/implementations/LinearAlgebra.jl:365 [inlined]
 [3] _mul!
   @ ~/.julia/packages/MutableArithmetics/Lnlkl/src/dispatch.jl:142 [inlined]
 [4] mul!
   @ ~/.julia/packages/MutableArithmetics/Lnlkl/src/dispatch.jl:157 [inlined]
 [5] *(A::Matrix{ComplexF64}, x::Vector{VariableRef})
   @ LinearAlgebra ~/julia-1.8.1/share/julia/stdlib/v1.8/LinearAlgebra/src/matmul.jl:56
 [6] top-level scope
   @ REPL[19]:1
```

### PR DESCRIPTION
**Pull request by odow**
Closes #3071

### CODE REVIEW

File: test/operator.jl [hunk 1]
```diff
@@ -549,6 +549,25 @@ function test_higher_level(ModelType, ::Any)
     end
 end
 
+function test_Model_complex_mult_variable(::Any, ::Any)
+    model = Model()
+    @variable(model, x[1:3])
+    A = rand(ComplexF64, 3,3)
```
Comment (odow) [inline test/operator.jl:555]:
```suggestion
    A = rand(ComplexF64, 3, 3)
```
