### PR TITLE
Fix constructing an array of Parameter variables

### LINKED ISSUE #3523: More Parameter woes
x-ref: https://discourse.julialang.org/t/creating-matrix-parameters-in-jump/104159

I thought I fixed this in https://github.com/jump-dev/JuMP.jl/pull/3473, but it turns out there are few other methods I must be missing. The lack of interfaces in Julia is a problem, because it makes it hard to know if you've implemented everything and there's no way to really test without enumerating every possible combination.

```Julia
julia> using JuMP

julia> model = Model();

julia> @variable(model, x1[1:2, 1:2] in Parameter(0.0))
ERROR: MethodError: no method matching build_variable(::JuMP.var"#_error#111"{LineNumberNode}, ::Matrix{ScalarVariable{Float64, Float64, Float64, Float64}}, ::Parameter{Float64})

Closest candidates are:
  build_variable(::Function, ::VariableInfo, ::Any...; kwargs...)
   @ JuMP ~/.julia/dev/JuMP/src/macros.jl:2039
  build_variable(::Function, ::AbstractArray{<:ScalarVariable}, ::MathOptInterface.AbstractScalarSet)
   @ JuMP ~/.julia/dev/JuMP/src/macros.jl:2188
  build_variable(::Function, ::AbstractArray{<:ScalarVariable}, ::AbstractArray{<:MathOptInterface.AbstractScalarSet})
   @ JuMP ~/.julia/dev/JuMP/src/macros.jl:2173
  ...

Stacktrace:
 [1] macro expansion
   @ ~/.julia/dev/JuMP/src/macros.jl:1218 [inlined]
 [2] top-level scope
   @ REPL[17]:1

julia> @variable(model, x2[i = 1:2, j = 1:2] in Parameter(i + j))
2×2 Matrix{VariableRef}:
 x2[1,1]  x2[1,2]
 x2[2,1]  x2[2,2]

julia> is_parameter.(x2)
2×2 BitMatrix:
 0  0
 0  0

julia> @variable(model, x3[i = 1:2, j = [:A, :B]] in Parameter(i))
2-dimensional DenseAxisArray{VariableRef,2,...} with index sets:
    Dimension 1, Base.OneTo(2)
    Dimension 2, [:A, :B]
And data, a 2×2 Matrix{VariableRef}:
 x3[1,A]  x3[1,B]
 x3[2,A]  x3[2,B]

julia> is_parameter.(x3)
2-dimensional DenseAxisArray{Bool,2,...} with index sets:
    Dimension 1, Base.OneTo(2)
    Dimension 2, [:A, :B]
And data, a 2×2 Matrix{Bool}:
 0  0
 0  0

julia> @variable(model, x4[i = 1:2, j = i:2] in Parameter(i + j))
JuMP.Containers.SparseAxisArray{VariableRef, 2, Tuple{Int64, Int64}} with 3 entries:
  [1, 1]  =  x4[1,1]
  [1, 2]  =  x4[1,2]
  [2, 2]  =  x4[2,2]

julia> is_parameter.(x4)
JuMP.Containers.SparseAxisArray{Bool, 2, Tuple{Int64, Int64}} with 3 entries:
  [1, 1]  =  false
  [1, 2]  =  false
  [2, 2]  =  false
```

### PR DESCRIPTION
**Pull request by odow**
Closes #3523

### CODE REVIEW

File: test/test_variable.jl [hunk 1]
```diff
@@ -1536,4 +1536,23 @@ function test_missing_variable_constraint_errors()
     return
 end
 
+function test_parameter_arrays()
+    model = Model();
```
Comment (odow) [inline test/test_variable.jl:1540]:
```suggestion
    model = Model()
```
