### PR TITLE
Fix performance of Containers.rowtable

### LINKED ISSUE #3404: `Containers.rowtable` is slow on Julia 1.9
Hi,

I have been working with the JuMP.Containers.rowtable function to write my results to CSV files. I noticed that the performance of this function seems to degrade when working with large scale models.
he original rowtable function is:

```julia
function rowtable(
    f::Function,
    x::Union{Array,DenseAxisArray,SparseAxisArray};
    header::Vector{Symbol} = Symbol[],
)
    if isempty(header)
        header = Symbol[Symbol("x$i") for i in 1:ndims(x)]
        push!(header, :y)
    end
    got, want = length(header), ndims(x) + 1
    if got != want
        error(
            "Invalid number of column names provided: Got $got, expected $want.",
        )
    end
    names = tuple(header...)
    return [NamedTuple{names}((args..., f(x[i]))) for (i, args) in _rows(x)]
end
```
While investigating this, I found that replacing the Tuple with a Vector when splatting and concatenating into the NamedTuple constructor resulted in a substantial improvement. Specifically, changing this line:
`return [NamedTuple{names}((args..., f(x[i]))) for (i, args) in _rows(x)]`
to this
 `return [NamedTuple{names}([args..., f(x[i])]) for (i, args) in _rows(x)]`. 
resulted in a roughly 20x speedup in my use-case.

Here is a benchmark example:

```julia
using JuMP
using JuMP.Containers
using BenchmarkTools
using HiGHS
using DataFrames
using Random


N = 100
NN = 50

cost = rand(N, NN)
cap = rand(1:20, NN)
demand = rand(50:100, N)

model = Model(HiGHS.Optimizer)
@variable(model, 0 <= x[i=1:N, j=1:NN] <= cap[j], container = DenseAxisArray)
@variable(model, y[i=1:N, j=1:NN; isodd(i+j)], container = SparseAxisArray)

@objective(model, Min, sum(cost[i,j] * x[i,j] for i in 1:N, j in 1:NN))
@constraint(model, [i=1:N], sum(x[i,j] for j in 1:NN) == demand[i])
@constraint(model, [i=1:N], sum(x[i,j] for j in 1:NN) == demand[i])
optimize!(model)
### Benchmarks ###



header=[:a, :b, :value]

_rows(x::DenseAxisArray) = zip(vec(eachindex(x)), Iterators.product(axes(x)...))
_rows(x::SparseAxisArray) = zip(eachindex(x.data), keys(x.data))

function test(
    f::Function,
    x::Union{Array,DenseAxisArray,SparseAxisArray};
    header::Vector{Symbol} = Symbol[],
)
    if isempty(header)
        header = Symbol[Symbol("x$i") for i in 1:ndims(x)]
        push!(header, :y)
    end
    got, want = length(header), ndims(x) + 1
    if got != want
        error(
            "Invalid number of column names provided: Got $got, expected $want.",
        )
    end
    names = tuple(header...)
    return [NamedTuple{names}([args..., f(x[i])]) for (i, args) in _rows(x)]
end



@btime JuMP.Containers.rowtable(value, $x, header=$header)
# 389.150 ms (200016 allocations: 6.61 MiB)
@btime test(value, $x, header=$header)
# 5.514 ms (105016 allocations: 3.03 MiB)

@btime JuMP.Containers.rowtable(value, $y, header=$header)
#194.082 ms (100010 allocations: 3.19 MiB)
@btime test(value, $y, header=$header)
#2.753 ms (52510 allocations: 1.39 MiB)
```

 This change seems to significantly improve the performance of the rowtable function without altering its functionality.

### PR DESCRIPTION
**Pull request by odow**
Closes #3404.

Julia 1.6

```julia
julia> using JuMP.Containers

julia> Containers.@container(x[i=1:100, j=1:50], i + j);

julia> function foo(x, header)
           names = tuple(header...)
           return [NamedTuple{names}((args..., x[i])) for (i, args) in Containers._rows(x)]
       end
foo (generic function with 1 method)

julia> function bar(x, header)
           elements = [(args..., x[i]) for (i, args) in Containers._rows(x)]
           return NamedTuple{tuple(header...)}.(elements)
       end
bar (generic function with 1 method)

julia> @assert foo(x, [:i, :j, :k]) == bar(x, [:i, :j, :k])

julia> @time foo(x, [:i, :j, :k]);
  0.006314 seconds (30.02 k allocations: 1.597 MiB)

julia> @time bar(x, [:i, :j, :k]);
  0.000154 seconds (23 allocations: 502.297 KiB)
```

Julia 1.9

```Julia
julia> using JuMP.Containers

julia> Containers.@container(x[i=1:100, j=1:50], i + j);

julia> function foo(x, header)
           names = tuple(header...)
           return [NamedTuple{names}((args..., x[i])) for (i, args) in Containers._rows(x)]
       end
foo (generic function with 1 method)

julia> function bar(x, header)
           elements = [(args..., x[i]) for (i, args) in Containers._rows(x)]
           return NamedTuple{tuple(header...)}.(elements)
       end
bar (generic function with 1 method)

julia> @assert foo(x, [:i, :j, :k]) == bar(x, [:i, :j, :k])

julia> @time foo(x, [:i, :j, :k]);
  0.378728 seconds (140.02 k allocations: 5.545 MiB)

julia> @time bar(x, [:i, :j, :k]);
  0.000079 seconds (18 allocations: 482.516 KiB)
```

I don't understand the reason for the regression in 1.9. But this is better regardless.

### CODE REVIEW

File: src/Containers/tables.jl [hunk 1]
```diff
@@ -61,8 +61,8 @@ function rowtable(
             "Invalid number of column names provided: Got $got, expected $want.",
         )
     end
-    names = tuple(header...)
-    return [NamedTuple{names}((args..., f(x[i]))) for (i, args) in _rows(x)]
+    elements = [(args..., x[i]) for (i, args) in Containers._rows(x)]
```
Comment (odow) [inline src/Containers/tables.jl:64]:
```suggestion
    elements = [(args..., f(x[i])) for (i, args) in Containers._rows(x)]
```

**Comment by odow** [comment]
Just to close the loop on the original benchmark:

Previously

```julia
julia> @btime JuMP.Containers.rowtable($value, $x, header=$header);
  371.580 ms (210016 allocations: 7.07 MiB)

julia> @btime test($value, $x, header=$header);
  6.915 ms (105016 allocations: 3.03 MiB)

julia> @btime JuMP.Containers.rowtable($value, $y, header=$header);
  187.218 ms (105010 allocations: 3.41 MiB)

julia> @btime test($value, $y, header=$header);
  3.433 ms (52510 allocations: 1.39 MiB)
```

This PR

```Julia
julia> @btime JuMP.Containers.rowtable(value, $x, header=$header);
  2.349 ms (55025 allocations: 1.46 MiB)

julia> @btime test(value, $x, header=$header);
  6.906 ms (105016 allocations: 3.03 MiB)

julia> @btime JuMP.Containers.rowtable(value, $y, header=$header);
  1.211 ms (27518 allocations: 625.70 KiB)

julia> @btime test(value, $y, header=$header);
  3.354 ms (52510 allocations: 1.39 MiB)
```
